"""add cierrocaja table

Revision ID: 58d4db69c677
Revises: c34fdc6a1df2
Create Date: 2026-08-19 02:55:06.075055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58d4db69c677'
down_revision: Union[str, None] = 'c34fdc6a1df2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cierres_caja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('fecha_apertura', sa.DateTime(), nullable=True),
    sa.Column('fecha_cierre', sa.DateTime(), nullable=True),
    sa.Column('monto_esperado', sa.Float(), nullable=True),
    sa.Column('monto_real', sa.Float(), nullable=True),
    sa.Column('diferencia', sa.Float(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('notas', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cierres_caja_id'), 'cierres_caja', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cierres_caja_id'), table_name='cierres_caja')
    op.drop_table('cierres_caja')
    # ### end Alembic commands ###
