"""create auditoria table fixed

Revision ID: 90d5ac9f461b
Revises: 58d4db69c677
Create Date: 2026-08-19 23:16:52.376889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90d5ac9f461b'
down_revision: Union[str, None] = '58d4db69c677'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('sucursal_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(), nullable=True),
    sa.Column('detalles', sa.String(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditoria_id'), 'auditoria', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auditoria_id'), table_name='auditoria')
    op.drop_table('auditoria')
    # ### end Alembic commands ###
