"""add payment method to estadia

Revision ID: ab35d88bd0a4
Revises: 90d5ac9f461b
Create Date: 2026-08-20 13:25:27.465519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab35d88bd0a4'
down_revision: Union[str, None] = '90d5ac9f461b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estadias', sa.Column('metodo_pago', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estadias', 'metodo_pago')
    # ### end Alembic commands ###
