"""add category rates

Revision ID: c34fdc6a1df2
Revises: 6e2e55963bc5
Create Date: 2026-07-29 18:27:27.630562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c34fdc6a1df2'
down_revision: Union[str, None] = '6e2e55963bc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sucursales', sa.Column('tarifa_auto', sa.Float(), nullable=True))
    op.add_column('sucursales', sa.Column('tarifa_moto', sa.Float(), nullable=True))
    op.add_column('sucursales', sa.Column('tarifa_camioneta', sa.Float(), nullable=True))
    op.add_column('sucursales', sa.Column('fraccion_minutos', sa.Integer(), nullable=True))
    op.drop_column('sucursales', 'tarifa_hora')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sucursales', sa.Column('tarifa_hora', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('sucursales', 'fraccion_minutos')
    op.drop_column('sucursales', 'tarifa_camioneta')
    op.drop_column('sucursales', 'tarifa_moto')
    op.drop_column('sucursales', 'tarifa_auto')
    # ### end Alembic commands ###
