"""add percentage discount to towers

Revision ID: e9c10c2392bd
Revises: 6a555aeb1f5f
Create Date: 2026-04-20 04:08:04.884149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9c10c2392bd'
down_revision: Union[str, None] = '6a555aeb1f5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('torres', sa.Column('porcentaje_descuento', sa.Float(), nullable=True))
    op.drop_column('torres', 'aplica_descuento')
    op.add_column('vehiculos', sa.Column('tipo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehiculos', 'tipo')
    op.add_column('torres', sa.Column('aplica_descuento', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('torres', 'porcentaje_descuento')
    # ### end Alembic commands ###
