"""add_permissions_and_business_rules

Revision ID: f0c2f197055a
Revises: e9c10c2392bd
Create Date: 2026-06-10 01:18:33.094163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0c2f197055a'
down_revision: Union[str, None] = 'e9c10c2392bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sucursales', sa.Column('tiempo_cortesia_min', sa.Integer(), nullable=True))
    op.add_column('usuarios', sa.Column('permisos', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'permisos')
    op.drop_column('sucursales', 'tiempo_cortesia_min')
    # ### end Alembic commands ###
